# Generated by Codex on 2026-05-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_management_profiles(apps, schema_editor):
    User = apps.get_model('urbanease', 'User')
    ManagementProfile = apps.get_model('urbanease', 'ManagementProfile')

    for user in User.objects.filter(role='ADMIN'):
        ManagementProfile.objects.get_or_create(
            user=user,
            defaults={
                'department': 'Society Management',
                'designation': 'Manager',
                'phone_number': '',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('urbanease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Management'), ('RESIDENT', 'Resident'), ('SECURITY', 'Security')], default='RESIDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='ManagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Society Management', max_length=50)),
                ('designation', models.CharField(default='Manager', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_management_profiles, migrations.RunPython.noop),
    ]
